project:
  type: website
  output-dir: docs

website:
  title: "fridarivera11.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
          - text: "Ship Wrecks"
            href: ship-wrecks.html
          - text: "Parental Leave"
            href: parental-leave.html
          - text: "UK Baby Names"
            href: uk-baby-names.html
          - text: "Love Island USA"
            href: love-island.html
          - text: "Market Indicator Explorer"
            href: market-index.html
          - text: "Foundation Shades"
            href: foundation-shades.html

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



