project:
  type: website
  output-dir: docs

website:
  title: "fridarivera11.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
          - text: "Ship Wrecks"
            href: project.html
          - text: "Parental Leave"
          - text: "UK Baby Names"

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



