project:
  type: website
  output-dir: docs

website:
  title: "fridarivera11.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
          - text: "Ship Wrecks"
            href: ship-wrecks
          - text: "Parental Leave"
            href: parental-leave
          - text: "UK Baby Names"
            href: UK-baby-names

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



