---
title: "Love Island USA"
author: "Frida Rivera"
date: July 23, 2026
format:
 html:
   embed-resources: true
   code-fold: true
execute:
 warning: false
 message: false

---
This data was extracted from Wikipedia Love Island USA all seasons. Much of this code was written by Emil Hviltfeldt in his <a href = "https://emilhvitfeldt.com/post/love-island-connections/" target ="_blank">Love Island Connections</a> blog.

```{r}
library(tidyverse)
library(rvest)
library(jsonlite)
library(ggraph)
library(tidygraph)
library(igraph)


chart_graph <- function(data) {
as_tbl_graph(data, directed = FALSE) |>
 ggraph(layout = "fr") +
   geom_edge_link() +
   geom_node_point() +
   geom_node_text(aes(label = name), repel = TRUE) +
   theme_graph() +
   theme(
     plot.background = element_rect(fill = "transparent", color = NA),
     panel.background = element_rect(fill = "transparent", color = NA)
)
}

```

```{r}
url7 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_7"
url8 <- "https://en.wikipedia.org/wiki/Love_Island_USA_season_8"

extract_couples <- function(url) {
  page <- read_html(url)
  all_tables <- page |> html_elements("table.wikitable") # |> html_table()
  coupling_table <- all_tables[[2]]

  rows <- coupling_table |>
   html_element("tbody") |>
   html_elements("tr")

  rows <- rows[-c(1, 2, length(rows)-c(0:6))]

  names <- rows |>
   html_elements("th") |>
   html_text() |>
   str_trim()

  extract_matches <- function(row) {
   row |>
     html_elements("td") |>
     html_text() |>
     str_trim()
 }
 
 map(rows, extract_matches) |>
  map2(names, ~ tibble(x = .y, y = .x)) |>
  list_rbind() |>
  filter(!str_detect(y, "\\(")) |>
  filter(!str_detect(y, "\\)")) |>
  filter(!str_detect(y, "\\&")) |>
  filter(!str_detect(y, "save")) |>
  filter(!str_detect(y, "dump")) |>
  filter(!str_detect(y, "100k")) |>
  filter(!str_detect(y, "Saved")) |>
  filter(
    y != "N/A", 
    y != "Not in Villa", 
    y != "Single",
    y != "Finalist", 
    y != "Safe", 
    y != "Vulnerable", 
    y!= "Eliminated", 
    y != "Not inVilla",
    y != "Immune"
    )
}

```


```{r}
li_data <- paste0("https://en.wikipedia.org/wiki/Love_Island_USA_season_", 1:8) |>
  map(extract_couples) |>
  list_rbind(names_to = "season") |>
  select(x, y, season)


write_csv(li_data,"li_data.csv")

```

These plots show the coupling between contestants on the show each season.

```{r}
set.seed(47)
for (season in sort(unique(li_data$season))) {
 cat("\n\n## Season", season, "\n\n")
 print(chart_graph(li_data[li_data$season == season, ]))
}

chart_graph(li_data |> filter(season == 8))
```

::: {.panel-tabset}

```{r}
#| label: graph-tabset
#| results: asis
#| dev.args: !expr list(bg = "transparent")

set.seed(1234)

for (season in sort(unique(li_data$season))) {
  cat("\n\n## Season", season, "\n\n")
  print(chart_graph(li_data[li_data$season == season, ]))
}
```

::: 
